---
- name: Create smokeping config volume
  community.docker.docker_volume:
    name: "{{ app_smokeping_docker_volume_config }}"

- name: Create smokeping data volume
  community.docker.docker_volume:
    name: "{{ app_smokeping_docker_volume_data }}"

- name: Ensure smokeping image is pulled
  community.docker.docker_image:
    name: "{{ app_smokeping_docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove smokeping container
  community.docker.docker_container:
    name: "{{ app_smokeping_docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on smokeping container
  community.docker.docker_container_info:
    name: "{{ app_smokeping_docker_container }}"
  register: result

- name: Create smokeping container
  community.docker.docker_container:
    env:
     TZ: "{{app_smokeping_tz}}"
    image: "{{ app_smokeping_docker_image }}"
    mounts:
     - source: "{{ app_smokeping_docker_volume_config }}"
       target: /config
     - source: "{{ app_smokeping_docker_volume_data }}"
       target: /data
    name: "{{ app_smokeping_docker_container }}"
    networks:
     - name: "{{ app_smokeping_docker_network }}"
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
