---
- name: Create smokeping config volume
  community.docker.docker_volume:
    name: app_smokeping_config

- name: Create smokeping data volume
  community.docker.docker_volume:
    name: app_smokeping_data

- name: Ensure linuxserver/smokeping image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/smokeping
    source: pull
    force_source: yes
  register: pulled

- name: Remove smokeping container
  community.docker.docker_container:
    name: smokeping
    state: absent
  when: pulled.changed

- name: Get infos on smokeping container
  community.docker.docker_container_info:
    name: smokeping
  register: result

- name: Create smokeping container
  community.docker.docker_container:
    env:
     TZ: "{{app_smokeping_tz}}"
    image: lscr.io/linuxserver/smokeping
    mounts:
     - source: app_smokeping_config
       target: /config
     - source: app_smokeping_data
       target: /data
    name: smokeping
    networks:
     - name: app-network
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
